{{- if .Values.ConfigMap }}

{{- $release_namespace := .Release.namespace }}
{{- $labels := include "base.labels" . }}
{{- $configFiles := (.Files.Glob "config/*").AsConfig }}

{{- with .Values.ConfigMap }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

data:
  {{- $configFiles | nindent 2 }}
  {{- with .data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

{{- with .binaryData }}
binaryData:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}
{{- end }}