{{- if .Values.CronJob }}

{{- $app_name := default (include "demo.name" .) .Values.CronJob.name }}
{{- $release_namespace := .Release.namespace }}
{{- $release_name := .Release.name }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.CronJob }}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $app_name }}
  namespace: {{ $release_namespace }}

  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  schedule: {{ required "schedule is required" .schedule | quote }}
  concurrencyPolicy: {{ .concurrencyPolicy | default "Allow" | quote }}
  failedJobsHistoryLimit: {{ default 1 .failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ default 3 .successfulJobsHistoryLimit }}
  suspend: {{ default false .suspend }}
  startingDeadlineSeconds: {{ default nil .startingDeadlineSeconds | quote }}

  {{- with .jobTemplate }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $app_name }}
        app.kubernetes.io/instance: {{ $release_name }}
        {{- with .labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
    
    spec:
      backoffLimit: {{ default 6 .backoffLimit }}
      activeDeadlineSeconds: {{ default nil .activeDeadlineSeconds | quote }}
      completions: {{ default nil .completions | quote }}
      manualSelector: {{ default nil .manualSelector | quote }}
      parallelism: {{ default nil .parallelism | quote }}

      {{- with .template }}
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ $app_name }}
            app.kubernetes.io/instance: {{ $release_name }}
            {{- with .labels }}
              {{- toYaml . | nindent 14 }}
            {{- end }}

        spec:
          {{- include "pod" . | nindent 10 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}