{{- if .Values.Deployment }}

{{- $release_namespace := .Release.Namespace }}
{{- $release_name := .Release.Name }}
{{- $labels := include "base.labels" . }}

{{- with .Values.Deployment }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $release_name }}-{{ required ".Deployment.name is required" .name }}
  namespace: {{ $release_namespace }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ required "No. of replicas are required" .replicas }}
  minReadySeconds: {{ default nil .minReadySeconds | quote }}
  progressDeadlineSeconds: {{ default nil .progressDeadlineSeconds | quote }}
  paused: {{ default nil .paused | quote }}
  revisionHistoryLimit: {{ default 10 .revisionHistoryLimit }}
  
  {{- with .strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
{{ $labels | indent 6 }}
      {{- with .labels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}

  {{- with .template }}
  template:
    metadata:
      labels:
{{ $labels | indent 8 }}
        {{- with .labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
    {{- include "pod" . | nindent 6 }}
            
  {{- end }}
{{- end }}
{{- end }}