{{- if .Values.Job }}

{{- $release_namespace := .Release.namespace }}
{{- $labels := include "base.labels" . }}

{{- with .Values.Job }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  namespace: {{ $release_namespace }}

  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  backoffLimit: {{ default 6 .backoffLimit }}
  activeDeadlineSeconds: {{ default nil .activeDeadlineSeconds | quote }}
  completions: {{ default nil .completions | quote }}
  manualSelector: {{ default nil .manualSelector | quote }}
  parallelism: {{ default nil .parallelism | quote }}
  ttlSecondsAfterFinished: {{ default nil .ttlSecondsAfterFinished | quote }}

  {{- with .template }}
  template:
    metadata:
      labels:
{{ $labels | indent 8 }}
        {{- with .labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
    {{- include "pod" . | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}