{{- if .Values.StorageClass }}

{{- $app_name := default (include "demo.name" .) .Values.StorageClass.name }}
{{- $labels := include "demo.labels" . }}

{{- with .Values.StorageClass }}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $app_name }}
  
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ $labels | indent 4 }}
  {{- with .labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

reclaimPolicy: {{ .reclaimPolicy | default "Delete" | quote }}
volumeBindingMode: {{ .volumeBindingMode | default "VolumeBindingImmediate" | quote }}
provisioner: {{ default nil .provisioner | quote }}
allowVolumeExpansion: {{ default nil .allowVolumeExpansion | quote }}

{{- with .mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .allowedTopologies }}
allowedTopologies:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}
{{- end }}